# Generated by Django 5.1 on 2024-10-07 15:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contact_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="IT"
            ),
        ),
    ]
