# Generated by Django 5.1 on 2024-10-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_contact_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
