# Generated by Django 5.1 on 2024-09-05 12:16

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_main_image_alter_property_main_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
