# Generated by Django 5.1 on 2024-10-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_alter_property_location_alter_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_sold",
            field=models.BooleanField(default=False, verbose_name="Sold Status"),
        ),
    ]
