# Generated by Django 5.1 on 2024-10-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_remove_property_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.CharField(default="Upon Request", max_length=20),
        ),
    ]
