# Generated by Django 5.1 on 2024-10-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_alter_property_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="price",
        ),
    ]
